DROP TABLE ATTACHMENTS;

DROP TABLE USER_VERIFICATION;

DROP TABLE EVENTS;

DROP TABLE DELETED_MESSAGES;

DROP TABLE ACCESS;

DROP TABLE DEVICES;

DROP TABLE BLOCK_LIST;

DROP TABLE REPORTS;

DROP TABLE MESSAGES;

DROP TABLE COMMUNITY_MEMBERS;

DROP TABLE COMMUNITIES;

DROP TABLE USERS;

CREATE TABLE USERS(
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    PHONE VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(40) NOT NULL,
    FIRST_NAME VARCHAR(20) NOT NULL DEFAULT '',
    LAST_NAME VARCHAR(20) NOT NULL DEFAULT '',
    MIDDLE_NAME VARCHAR(20) NOT NULL DEFAULT '',
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 0,
    IS_REPORTED TINYINT(1) NOT NULL DEFAULT 0,
    IS_BLOCKED TINYINT(1) NOT NULL DEFAULT 0,
    PREFERENCES TEXT NOT NULL DEFAULT '',
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE COMMUNITIES (
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    TITLE VARCHAR(40) NOT NULL,
    COMMUNITY_ID VARCHAR(45) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    DELETED_AT DATETIME,
    PRIMARY KEY(ID)
);

CREATE TABLE COMMUNITY_MEMBERS (
    COMMUNITY_ID INT NOT NULL UNSIGNED,
    USER_ID INT NOT NULL,
    TYPE ENUM('Single', 'Group') NOT NULL,
    IS_QUITTED TINYINT(0) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY(COMMUNITY_ID, USER_ID),
    FOREIGN KEY(COMMUNITY_ID) REFERENCES COMMUNITIES(COMMUNITY_ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE MESSAGES(
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    UUID BINARY(16) NOT NULL DEFAULT UUID(),
    COMMUNITY_ID INT NOT NULL UNSIGNED,
    SENDER_ID INT NOT NULL,
    MESSAGE_TYPE ENUM('Text', 'Image', 'Video', 'Audio') NOT NULL,
    MESSAGE VARCHAR(255) NOT NULL DEFAULT '',
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    DELETED_AT DATETIME,
    PRIMARY KEY(ID),
    FOREIGN KEY(COMMUNITY_ID) REFERENCES COMMUNITIES(COMMUNITY_ID),
    FOREIGN KEY(SENDER_ID) REFERENCES COMMUNITY_MEMBERS(USER_ID)
);

CREATE TABLE REPORTS (
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    REPORT_TYPE VARCHAR(45) NOT NULL,
    COMMENTS TEXT NOT NULL,
    STATUS ENUM('PENDING', 'RESOLVED') NOT NULL DEFAULT 'PENDING',
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY(MEMBER_ID) REFERENCES COMMUNITY_MEMBERS(USER_ID)
);

CREATE TABLE BLOCK_LIST(
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    IS_BLOCKED TINY(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY(MEMBER_ID) REFERENCES COMMUNITY_MEMBERS(USER_ID)
);

CREATE TABLE DEVICES(
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    DEVICE_ID VARCHAR(255) NOT NULL,
    DEVICE_TOKEN VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
);

CREATE TABLE ACCESS(
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    DEVICE_ID INT NOT NULL,
    ACCESS_TOKEN VARCHAR(255) NOT NULL,
    LAST_LOGIN DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY(DEVICE_ID) REFERENCES DEVICES(DEVICE_ID)
);

CREATE TABLE DELETED_MESSAGES(
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    MESSAGE_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(MESSAGE_ID) REFERENCES MESSAGES(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE EVENTS(
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    EVENT_TYPE VARCHAR(255) NOT NULL,
    EVENT_ID VARCHAR(255) NOT NULL UNIQUE,
    CREATOR_ID INT NOT NULL UNSIGNED,
    COMMUNITY_ID INT NOT NULL UNSIGNED,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(CREATOR_ID) REFERENCES COMMUNITY_MEMBERS(USER_ID),
    FOREIGN KEY(COMMUNITY_ID) REFERENCES COMMUNITIES(ID)
);

CREATE TABLE USER_VERIFICATION(
    USER_ID INT NOT NULL UNIQUE,
    VERIFICATION_CODE VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE ATTACHMENTS(
    ID INT NOT NULL UNSIGNED AUTO_INCREMENT,
    MESSAGE_ID INT NOT NULL,
    THUMB_URL VARCHAR(255) NOT NULL,
    FILE_URL VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(MESSAGE_ID) REFERENCES MESSAGES(ID)
);